In [1]:
!pip install gym

  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
  Running setup.py bdist_wheel for gym: started
  Running setup.py bdist_wheel for gym: finished with status 'done'
  Stored in directory: C:\Users\Simi\AppData\Local\pip\Cache\wheels\cb\14\71\f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: C:\Users\Simi\AppData\Local\pip\Cache\wheels\bf\c9\a3\c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
Successfully built gym future


In [1]:
import gym

env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.02409646 -0.00204454 -0.00378647  0.03147532]
[ 0.02405557 -0.19711199 -0.00315697  0.32296117]
[ 0.02011333 -0.00194522  0.00330226  0.02928434]
[ 0.02007443  0.19312922  0.00388794 -0.26235486]
[ 0.02393701 -0.00204802 -0.00135915  0.03155183]
[ 0.02389605  0.1930934  -0.00072812 -0.26155961]
[ 0.02775792  0.38822574 -0.00595931 -0.55447211]
[ 0.03552243  0.58343086 -0.01704875 -0.84902662]
[ 0.04719105  0.77878112 -0.03402928 -1.14702152]
[ 0.06276667  0.97433049 -0.05696971 -1.45017844]
[ 0.08225328  1.17010444 -0.08597328 -1.76010298]
[ 0.10565537  1.36608805 -0.12117534 -2.07823763]
[ 0.13297713  1.17238471 -0.16274009 -1.82535163]
[ 0.15642483  0.97939972 -0.19924713 -1.58733367]
Episode finished after 14 timesteps
[ 0.03531595  0.0280042  -0.01153086  0.00037964]
[ 0.03587603 -0.1669505  -0.01152326  0.28940225]
[ 0.03253702 -0.36190625 -0.00573522  0.5784287 ]
[ 0.0252989  -0

[-0.01654314  0.38293455 -0.10925204 -0.86579028]
[-0.00888445  0.18945557 -0.12656784 -0.60935835]
[-0.00509534 -0.00369108 -0.13875501 -0.35906753]
[-0.00516916  0.19310253 -0.14593636 -0.69208405]
[ -1.30711234e-03   2.74337702e-04  -1.59778041e-01  -4.48669515e-01]
[-0.00130163  0.19725286 -0.16875143 -0.78714895]
[ 0.00264343  0.39424117 -0.18449441 -1.12781193]
[ 0.01052825  0.20195136 -0.20705065 -0.89820637]
Episode finished after 20 timesteps
[-0.04325989  0.03716168  0.04002425  0.04770353]
[-0.04251666  0.23168754  0.04097832 -0.23208758]
[-0.03788291  0.03600474  0.03633657  0.07323446]
[-0.03716281  0.23058743  0.03780126 -0.20776631]
[-0.03255106  0.0349459   0.03364593  0.09659726]
[-0.03185215  0.22956988  0.03557788 -0.18528344]
[-0.02726075  0.03395742  0.03187221  0.11840726]
[-0.0265816   0.22860856  0.03424035 -0.16405232]
[-0.02200943  0.03301361  0.03095931  0.13923283]
[-0.02134916  0.22767878  0.03374397 -0.14352441]
[-0.01679558  0.03209022  0.03087348  0.1596

[ 0.18610487  2.0962639  -0.19152704 -2.55655231]
Episode finished after 44 timesteps
[-0.01295994  0.03785575 -0.04869859  0.00403312]
[-0.01220283 -0.15653519 -0.04861793  0.28096212]
[-0.01533353 -0.35093114 -0.04299868  0.55792344]
[-0.02235216 -0.15523279 -0.03184022  0.25200953]
[-0.02545681  0.04032901 -0.02680002 -0.05054393]
[-0.02465023  0.23582479 -0.0278109  -0.35156056]
[-0.01993374  0.04110915 -0.03484211 -0.06777539]
[-0.01911155  0.23671286 -0.03619762 -0.37124439]
[-0.0143773   0.43232987 -0.04362251 -0.67511747]
[-0.0057307   0.62803001 -0.05712486 -0.98120938]
[ 0.0068299   0.8238691  -0.07674905 -1.29127442]
[ 0.02330728  1.01987839 -0.10257454 -1.60696491]
[ 0.04370485  1.21605264 -0.13471383 -1.92978367]
[ 0.06802591  1.41233626 -0.17330951 -2.26102773]
Episode finished after 14 timesteps
[-0.00685335  0.03484761  0.04203638 -0.02547417]
[-0.0061564  -0.16085118  0.0415269   0.28016975]
[-0.00937343 -0.35654014  0.04713029  0.58565554]
[-0.01650423 -0.55228945  0.